config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  resources :posts 
    resources :comments
  # end
  
  get 'search', to: 'profiles#search'
  get '/notif', to: 'profiles#acceptnotif'
  get '/feed', to: 'profiles#feed'
  get '/followrequests', to: 'profiles#followrequests'
  resources :interests

  resources :rooms, except: [:show] do
    resources :messages
  end
  
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }
  as :user do

    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    



  end
  get 'users/:id/message', to: 'users#showmessage', as: 'usermessage'
  post '/users/:id', to: 'users#destroy'


  resources :users,only: [:destroy,:show]
  

  post 'users/:id/follow', to:"users#follow", as: "follow"
  post 'users/:id/unfollow', to:"users#unfollow", as: "unfollow"
  post 'users/:id/accept', to:"users#accept", as: "accept"
  post 'users/:id/decline', to:"users#decline", as: "decline" 
  post 'users/:id/cancel', to:"users#cancel", as: "cancel"
  
  root to: 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def search


    @current = current_user
    @query = params[:query]
    @interestquery=params[:interestquery]
    @experience = params[:filter]

    if @experience == ""
    # ----------------------------------------------------------------------

        @user_names = User.where("name LIKE ? AND city = ?", "%#{@query}%","#{@current.city}")


        if @query == ""
          @user_names=[]
        end

    # ------------------------------------------------------------------

      elsif  @experience != "" and @interestquery == ""
    @user_names=[]


    #____----------------------------------------

    else

    @interests = Interest.where("name LIKE ? AND experience = ?", "%#{@interestquery}%","#{@experience}")
    @user_ids = []
    @user_names=[]

        @interests.each do |interest|
          @user_ids.append(interest.user_id)
        end

        @user_ids.each do |id|
          @user=User.find(id)
          if @user.city == @current.city
               @user_names.append(@user)
          end
        end
    end

    # ------------------------------------------------------------------------------

  end

  def followrequests
    @current=current_user.follow_requests
  end

  def feed
    @current=current_user
    @followers=@current.followers
    @interests=@current.interests
    @all_users=[]

    
    
    # @interest = @interests[rand(@interests.length)]
      @interests.each do |interest| 
      @users=User.joins(:interests).where(interests: { name: interest.name })
      @interest_name=interest.name
      @object = { @interest_name => @users }
      @all_users.append(@object)
    # @user_ids.each do |id|
    #   @user=User.find(id)
    #   if @user != @current
    #     @all_users.append(@user)
    #     puts(@all_users)
      end

      
    # end

    
    @feedposts=[]
    @allposts=[]
    
    
    @interests.each do |interest| 

      @posts=Post.where("category LIKE ?", "%#{interest.name}%")
      @posts.each do |post|
        if @current.mutual_following_with?(post.user) || @current == (post.user)
          @feedposts.append(post)
        end
      end
      

      @posts.each do |post|
        @comment=post.comments.build
      end
      @allposts.concat(@posts).shuffle

      

    end
    @show_all_posts= params[:show_all_posts] == "1"

  
   

    
  end

  def acceptnotif
    @notif_users=[]
    @notif=current_user.store
    @notif.each do |notif|
      @user=User.find(notif)
      @notif_users.append(@user)
  end


  end

  private

  def getname(id)
    @name=User.find(id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/acceptnotif.html.erb
<div class="w-screen ">

<% if @notif_users.any? %>
<% @notif_users.reverse_each  do |user|%>
    <div class="border border-black w-1/2 rounded-md m-auto mt-5 flex items-center justify-evenly  ">

            <div class="flex w-20 h-20 p-4  rounded-full">
                <% if user.image.attached? %>
                    <%= link_to image_tag(user.image,class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%>
                <% else%>
                    <%=  link_to image_tag("account.jpg",class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%>
                 <% end %>
            </div>

            <div class="flex "><p class="font-bold ml-10 my-auto mr-1"><%= user.name %></p><span> accepted your request.</span></div>
             <span class="ml-2 hover:scale-105 duration-200 hover:underline hover:cursor-pointer">  <%= link_to "View Profile",user_path(user.id);%></span>


    </div>
<% end %>
<% else%>
                 
            <div class="text-center mt-10 "> No new Notifications.</div>

  <% end %>
</div>

app/views/profiles/feed.html.erb
<div class="w-fit mx-auto px-auto mt-10 flex-items-center justify-center">


<div class="bg-gray-200 h-16 w-[550px] flex justify-center items-center rounded-md">
<%= form_tag feed_path, id: 'allpost',class: 'flex',method: :get do %>

  <%= label_tag :show_all_posts, "EXPLORE BEYOND FEED ?",:class => ' mr-10 font-bold text-lg' %>
  <%# <label class="switch">
    <input type="checkbox" name="show_all_posts" id="switch" value="1" class="w-5 h-5 mr-10">
    <span class="slider round"></span>
</label> %>
  <span class="mx-auto"><%= check_box_tag :show_all_posts, 1, @show_all_posts,id:"switch",class: 'w-5 h-5 mr-10' %></span>
  <%= submit_tag "",id:"submitbtn" %>
<% end %>
</div>





<% if @allposts.any? %>


                <% (@show_all_posts ? @allposts : @feedposts).shuffle.each_with_index do |post,index|%>


                <div class="mt-10 mx-auto px-auto bg-slate-100 rounded px-5 pt-5 w-[550px]">
                <div class="flex h-16 items-center">
                        <div class="mb-3">
                                <% if post.user.image.attached?%>
                                    <%= image_tag(post.user.image,class:"flex object-cover w-12 h-12  rounded-full border-2 border-blue-600 ");%>
                                <% else%>
                                    <%= image_tag "account.jpg",class:"flex object-cover w-12 h-12  rounded-full border-2 border-blue-600";%>
                                <% end %>
                        </div>

                        <div class="flex flex-col ml-3">
                                <span class="font-bold <%= 'bg-blue-600 text-white rounded px-2' if post.user.mutual_following_with?(@current) || post.user == (@current)  %>"><%= post.user.name %></span>
                                <%= post.user.city %>
                        </div>

                        <div class="flex mb-12 ml-32 items-end">
                            <% if current_user.id != post.user.id %>
                                <% if current_user.following?(post.user)%>
                                    <%= button_to "Unfriend",unfollow_path(post.user),class:"flex border  w-32 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center mt-10"%>
                                <% elsif current_user.sent_follow_request_to?(post.user)%>
                                    <%= button_to "Cancel Friend Request",cancel_path(post.user),class:"flex border  w-44 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center mt-10"%>
                                <% elsif post.user.sent_follow_request_to?(current_user)%>
                                    <div class="flex mt-4">
                                                <%= button_to "Accept",accept_path(post.user),class:"border border-black text-white px-3 py-2 rounded bg-blue-500 hover:scale-90 duration-200 "%>
                                                <%= button_to "Decline",decline_path(post.user),class:"mr-5 ml-3 border border-black bg-red-600 text-white px-3 py-2 rounded  hover:scale-90 duration-200 "%>
                                    </div>    
                                <% else %>
                                    <%= button_to "Add Friend",follow_path(post.user),class:"flex border  w-32 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center mt-10"%>
                                <% end %>
                                <% end %>
                        </div>
                </div>
                

                <% if post.image.attached?%>
                <%= link_to post_path(post) do %>
                    <div class="w-96 h-fit "><%= image_tag (post.image) %></div>
                <% end %>
                <% end %>


                <%= turbo_frame_tag "likes_#{post.id}" do %>
                <div class="mt-3  flex flex-row  border-b pb-2 border-inherit items-center" > 
                <% like = current_user.likes.find_by(post: post)%>
                    <%#= render "likes/like", like: like, post: post, class: "invisible"%>
                
                <% if like.nil? %>
                    <%= button_to "Like", likes_path, params:{like: {post_id: post.id}},method: :post,class:"border py-1 px-5 bg-white text-blue-600 border-blue-600 hover:scale-90 duration-300 hover:border-red-600 hover:text-red-600 rounded" %>
                    
                <% else %>
                    <%= button_to "Unlike", like_path(like),method: :delete,class:"border py-1 px-5 bg-white text-blue-600 border-blue-600 hover:scale-90 duration-300 hover:border-red-600 hover:text-red-600 rounded" %>  
                <% end %>

                
                    <span class="font-bold ml-5 " ><%= post.likes.count%></span>
                
                
                <span class="font-bold ml-1">Likes </span></div>
            <%end %>


                <div class="flex pt-2 items-center">
                    <span class="font-bold bg-zinc-700 rounded-md px-4 py-1 text-white"><%= post.user.name %></span>
                    <span class="ml-3 font-semibold"><%= post.caption %></span>
                </div>

                <% comment = post.comments.build %>
                <%= render "comments/form", comment: comment%>
                <%= turbo_frame_tag "comments_#{post.id}" do %>
                <div class=" overflow-y-scroll h-fit min-h-fit max-h-32 mt-2 no " id="comments" >
                    <% post.comments.each do |comment|%>
                        
                            <%= render "comments/comment", comment: comment%>
                        
                    <% end %>
                </div>
                <% end %>

                <% if ((index) % 1 == 0) %>
                    <%if  @all_users.any? %>

                    <% @singleinterest = @all_users[rand(@all_users.length)]%>
                    
                    <% @singleinterest.each do |interest,users|%> 

                            <div class="mt-4 border-t-2 pt-4 border-t-2 pb-4">
                                    <p class="font-bold mb-4"> Check Out People interested in <%= interest %></p>


                                    <div class="flex   overflow-x-scroll max-w-3/4 mt-3  mx-auto ">

                                    <% users.shuffle.each do |user|%>

                                        <% if current_user != user %>
                                            <%= link_to user do %>
                                            <div class=" mx-3 py-2 px-4 flex flex-col items-start  hover:scale-105 duration-300 my-2">
                                            <div class="w-32 h-32">
                                                            <% if user.image.attached? %>
                                                                <%= link_to image_tag(user.image,class:"flex object-cover w-32 h-32  rounded-full"),user_path(user.id);%>
                                                            <% else%>
                                                                <%=  link_to image_tag("account.jpg",class:"flex object-cover w-32 h-32  rounded-full"),user_path(user.id);%>
                                                            <% end %>
                                            </div>
                                            <p class="mt-2 font-bold"><%= user.name %></p>
                                           </div>
                                            <% end %>
                                        
                                        <% end %>   
                                        <% end %>
                                        </div>

                            </div>

                    <% end %>
                    <% end %>
                <%end %>
                
                
                
                
                </div>

                <% end %>

        
<% end %>

</div>
<script>

        form = document.getElementById("allpost");
        console.log(form)
        switchbtn = document.getElementById("switch")
        console.log(switchbtn)
        submitbtn = document.getElementById("submitbtn")
        console.log(submitbtn)
        // errorblock = document.getElementById("error_explanation");

        switchbtn.addEventListener('change',(event)=>{         
          if (event.target.checked){       
              console.log("checked")
              submitbtn.click() 
          }
          else{
              console.log("Unchecked")
              submitbtn.click() 
          }
        })


        



</script>

app/views/profiles/followrequests.html.erb
<div class="w-screen h-screen items-center justify-center">

    <div class="w-screen h-screen items-center justify-center">


    <% if @current.any? %>
  


            <% @current.each do |request|%>

            

            

                <div class="mx-auto border border-black w-1/2 flex items-center justify-between mt-5 rounded-md">
                
                
                <div class="flex w-32 h-32 p-4  rounded-full">
                
                    <% if request.followerable.image.attached? %>
                        <%=link_to image_tag(request.followerable.image,class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(request.followerable.id);%> 
                    <% else%>
                        <%=link_to  image_tag("account.jpg",class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(request.followerable.id);%>
                    <% end %>
                
                </div>
                

                <p><span class="font-bold"><%=request.followerable.name%></span> wants to connect</p>
                <div class="flex">
                    <%= button_to "Accept",accept_path(request.followerable),class:"border border-black px-3 py-2 rounded hover:bg-blue-500 hover:scale-90 duration-200 hover:text-white"%>
                    <%= button_to "Decline",decline_path(request.followerable),class:"mr-5 ml-3 border border-black px-3 py-2 rounded hover:bg-red-600 hover:scale-90 duration-200 hover:text-white"%>
                </div>
                </div>
            

            

            <% end %>

    <% else%>
                 
            <div class="text-center mt-10"> No Pending Friend Requests !</div>
            
    <% end %>

    
    </div>


</div>

app/views/profiles/search.html.erb
<div class="items-center  justify-between flex w-screen">

  <div class="items-center justify-between flex flex-col  w-screen">

  <% if @user_names.any? %>

    <% @user_names.each do |user|%>

    <% if current_user.id != user.id %>
         
      <div class="flex w-1/2 border border-black items-center mt-5 mx-auto rounded-md justify-between">


      <%# Conditional Rendering of tyhe Profile Picture for each user %>
      <div class="flex">
      <div class="flex w-32 h-32 p-4  rounded-full">
        <% if user.image.attached? %>
             <%= link_to image_tag(user.image,class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%>
        <% else%>
          <%=  link_to image_tag("account.jpg",class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%>
      <% end %>
      </div>



      <h1 class="font-bold ml-10 my-auto"><%= user.name %></h1>
      

      </div>

  
      <%# Conditional rendering of the FRIEND button %>
      <% if current_user.following?(user)%>
          <%= button_to "Unfriend",unfollow_path(user),class:"flex border  w-28 h-7 mr-20 my-auto rounded bg-black text-white text-xs hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center"%>
      <% elsif current_user.sent_follow_request_to?(user)%>
          <%= button_to "Cancel Friend Request",cancel_path(user),class:"flex border  w-40 h-7 mr-20 my-auto rounded bg-black text-white text-xs hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center"%>
      <% elsif user.sent_follow_request_to?(current_user)%>
        <div class="flex">
                    <%= button_to "Accept",accept_path(user),class:"border border-black px-3 py-2 text-white rounded bg-blue-500 hover:scale-90 duration-200 "%>
                    <%= button_to "Decline",decline_path(user),class:"mr-5 ml-3 border border-black px-3 py-2 text-white rounded bg-red-600 hover:scale-90 duration-200 text-white"%>
        </div> 
      <% else %>
          <%= button_to "Add Friend",follow_path(user),class:"flex border  w-28 h-7 mr-20 my-auto rounded bg-black text-white text-xs hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center"%>
      <% end %>
           

      </div>

      <% end %>


  <% end %>
  <% else%>
                 
            <div class="text-center mt-10"> No Search Results ! Check your query and try again.</div>

  <% end %>
</div>



</div>