config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  resources :posts 
    resources :comments
  # end
  
  get 'search', to: 'profiles#search'
  get '/notif', to: 'profiles#acceptnotif'
  get '/feed', to: 'profiles#feed'
  get '/followrequests', to: 'profiles#followrequests'
  resources :interests

  resources :rooms, except: [:show] do
    resources :messages
  end
  
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }
  as :user do

    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    



  end
  get 'users/:id/message', to: 'users#showmessage', as: 'usermessage'
  post '/users/:id', to: 'users#destroy'


  resources :users,only: [:destroy,:show]
  

  post 'users/:id/follow', to:"users#follow", as: "follow"
  post 'users/:id/unfollow', to:"users#unfollow", as: "unfollow"
  post 'users/:id/accept', to:"users#accept", as: "accept"
  post 'users/:id/decline', to:"users#decline", as: "decline" 
  post 'users/:id/cancel', to:"users#cancel", as: "cancel"
  
  root to: 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    
    @comment.user_id = current_user.id
    @post=@comment.post
    @comment.save
    update_comment
    
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end

    def update_comment
      render turbo_stream:
      turbo_stream.replace("comments_#{@post.id}",
        partial: "comments/commentbox",
        locals: { comment: @comment, post: @post }
      )
    
      turbo_stream.replace("post_comments_#{@post.id}",
            partial: "comments/postcommentbox",
            locals: { comment: @comment, post: @post }
          )
        
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<turbo-frame id="comment-<%= comment.id %>">
<div id="<%= dom_id comment %>">
  <p class="mt-3 max-w-sm">
                          <span class="font-bold"><%= comment.user&.name %></span>
                          <span class="ml-2 w-2/3   whitespace-normal break-words truncate overflow-x-scroll font-light"><%= comment.body%></span>
  </p>
</div>
</turbo-frame>

app/views/comments/_commentbox.html.erb
<%= turbo_frame_tag "comments_#{post.id}" do %>
               
                <div class=" overflow-y-scroll h-fit min-h-fit max-h-32 mt-2 no" id="comments" >
                    <% post.comments.each do |comment|%>
                        
                            <%= render "comments/comment", comment: comment%>
                        
                    <% end %>
                    
                </div>
<% end %>

app/views/comments/_form.html.erb
<div class="w-96 ml-10"><%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.hidden_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.hidden_field :post_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %></div>

app/views/comments/_formforpost.html.erb
<div class="mt-3"><%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="">
    <%= form.hidden_field :post_id %>
  </div>

<div class="flex items-center justify-center ">
  <div class="">
    <%#= form.label :body %>
    <%= form.text_field :body,  placeholder: "Add a comment",class: "block shadow rounded-md border border-gray-200 outline-none w-80 " %>
  </div>

  <div class="invisible">
    <%= form.submit class: "rounded-lg bg-blue-600 text-white inline-block font-medium cursor-pointer", id:"submitBtn" %>
  </div></div>
<% end %></div>


<script>
submitBtn=document.getElementById("submitBtn")
submitBtn.addEventListener('click',(event)=>{         
          location.reload()
        })


</script>

app/views/comments/_postcommentbox.html.erb
<%= turbo_frame_tag "post_comments_#{post.id}" do %>
               
                <div class=" overflow-y-scroll h-fit min-h-fit max-h-32 mt-2 no" id="comments" >
                    <% post.comments.each do |comment|%>
                        
                            <%= render "comments/comment", comment: comment%>
                        
                    <% end %>
                    
                </div>
<% end %>

app/views/comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to 'New comment', new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to 'Back to comments', comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @comment %>

    <%= link_to 'Edit this comment', edit_comment_path(@comment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this comment', comment_path(@comment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to comments', comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>