config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  resources :posts 
    resources :comments
  # end
  
  get 'search', to: 'profiles#search'
  get '/notif', to: 'profiles#acceptnotif'
  get '/feed', to: 'profiles#feed'
  get '/followrequests', to: 'profiles#followrequests'
  resources :interests

  resources :rooms, except: [:show] do
    resources :messages
  end
  
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }
  as :user do

    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    



  end
  get 'users/:id/message', to: 'users#showmessage', as: 'usermessage'
  post '/users/:id', to: 'users#destroy'


  resources :users,only: [:destroy,:show]
  

  post 'users/:id/follow', to:"users#follow", as: "follow"
  post 'users/:id/unfollow', to:"users#unfollow", as: "unfollow"
  post 'users/:id/accept', to:"users#accept", as: "accept"
  post 'users/:id/decline', to:"users#decline", as: "decline" 
  post 'users/:id/cancel', to:"users#cancel", as: "cancel"
  
  root to: 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         scope :all_except, ->(user){where.not(id: user)}
         after_create_commit {broadcast_append_to "users"}
         has_many :messages, dependent: :destroy

         validates :contact_number, presence: true, format: { with: /\A\+91\d{10}\z/, message: "must be a Indian phone number" }
         # validates :city, presence: true

         # validate :skip_email_validation_if_name_is_blank

         def skip_email_validation_if_city_is_blank
           if city.blank?
             self.email = nil
             self.password = nil
             self.password_confirmation = nil
             self.contact_number = nil
             self.name = nil
           end
         end


         has_many :interests, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy

         

         followability

         def unfollow(user)
            followerable_relationships.where(followable_id: user.id).destroy_all
         end

         def self.ransackable_attributes(auth_object = nil)
            [ "email","name"]
          end

         
         def self.states
            CS.states(:IN)
         end
      
         def self.cities
            CS.cities(state, :IN ) || []
         end


         # def follow_request_accepted_by_someone(record);
         #    puts(record)
         # end


         def age
            now = Time.now.utc.to_date
            dob = self.date_of_birth.to_date
            age_in_years = now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
            age_in_years
          end

         has_one_attached :image, dependent: :destroy
         # follow_request_accepted_by_someone :follow_request_accepted_by
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  



  


  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # # POST /resource
  def create
    # debugger

    @user=params[:user]
    @username=params[:user][:name]
    user_params = params[:user][:state]
    @selected_state= user_params
    # random_string = SecureRandom.alphanumeric(8)s

   
    super
  end

  # # GET /resource/edit
  def edit
    
    # @user=current_user
    # user_params = params[:state]
    # @selected_state= user_params
    super
  end

  # # PUT /resource
  def update
    # debugger
    @user=params[:user]
    user_params = params[:user][:state]
    @selected_state= user_params
    super
  end

  # # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:state,:city,:area,:contact_number,:date_of_birth])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio,:image,:state,:city])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts=Post.where("user_id LIKE ?", "%#{@user.id}%")
    @state=@user.state
    @hash = CS.states(:in)
    @userstate=@hash[@state]
  end

  def showmessage
    if params[:id].present?
        @user=User.find(params[:id])
        @users = User.all_except(current_user)
        
        @room=Room.new
        # @rooms=Room.public_rooms
        @room_name=get_name(@user,current_user)
        @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

        @message = Message.new
        @messages = @single_room.messages.order(created_at: :asc)

        if current_user == @user
          flash[:alert] = "hey you got notification"
        end

        @followers = current_user.followers
        @q = params[:q]

        if @q.present?
          puts(@q)
           
            @followers = @followers.where("name LIKE ?", "%#{@q}%")
            puts (@followers)
        
        end
        

        render 'rooms/index'
    else
      redirect_to root_path, notice: "Room not found"
    end
  end

  

  # To delete the account
  def destroy
    @user = current_user
    @user.destroy
    flash[:success] = "Your account has been deleted."
    redirect_to root_path
  end
 
  def follow
    current_user.send_follow_request_to(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    make_it_a_unfriend_request
    current_user.unfollow(@user)
    redirect_to user_path(@user)
  end

  def accept
    current_user.accept_follow_request_of(@user)

    store=@user.store
    if store.length < 10
      store.push(current_user.id)
    else
      store.shift
      store.push(current_user.id)
    end
    @user.update(store: store)
      
    make_it_a_friend_request
    
    redirect_to user_path(@user)
  end

  def decline
    current_user.decline_follow_request_of(@user)
    redirect_to root_path
  end

  def cancel
    current_user.remove_follow_request_for(@user)
    redirect_to root_path
  end

  def fetch_country_states
    @states = CS.states(:IN)
    @cities = CS.cities(state)
  end




  private

  def set_user
    @user=User.find(params[:id])
  end

  def make_it_a_unfriend_request
    @user.unfollow(current_user) if @user.mutual_following_with?(current_user)
  end

  def make_it_a_friend_request
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
  end

  def get_name(user1, user2)
    user=[user1,user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="w-full h-32 flex items-center justify-between pl-10  border-b-2 border-slate-200">

    <div class="flex justify-evenly items-center">

    <div class="flex w-20 h-20 p-2  rounded-full">
                
        <% if user.image.attached? %>
            <%=link_to image_tag(user.image,class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%> 
        <% else%>
            <%=link_to  image_tag("account.jpg",class:"flex object-cover w-auto h-auto min-h-full min-w-full max-h-full  max-w-full rounded-full"),user_path(user.id);%>
        <% end %>
                
    </div>

    <div class="font-bold"><%= link_to user.name,"/users/#{user.id}/message"%></div>
    </div>
</div>

app/views/users/fetch_country_states.turbo_stream.erb
<% if @cities.present? %>
    <%= turbo_stream.replace "city_list" do %>
        <div class="field my-3 w-1/2 ml-2" id="city-list">
            <%= f.label :city %><br />
            <%= f.select :city, User.cities,{include_blank: true},class:"border border-black w-3/4 " %>
        </div>
    <% end %>
<% end %>

app/views/users/show.html.erb
<%= console %>
<% if user_signed_in? %> 
<div class="h-screen max-w-screen bg-gray-100 flex justify-around items-center">


<%# Conditional rendering of Profile picture  %>
<div class="w-1/2 flex items-center justify-center h-full flex-col">
 <div class="h-64 w-64 rounded-full ">
<% if @user.image.attached?%>
    <%= image_tag(@user.image,class:"flex object-cover w-auto h-auto min-h-full min-w-full rounded-full");%>
<% else%>
    <%= image_tag "account.jpg",class:"flex object-cover w-auto h-auto min-h-full min-w-full rounded-full";%>
<% end %>

</div>

<%# Conditional rendering of Edit Profile button %>
<% if current_user.id == @user.id %>
  <div class="flex border border-black w-48 h-10 items-center justify-center m-8 rounded-md bg-white hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white"><%= link_to "Edit Profile", edit_user_registration_path %></div> 
<% end %>

<%# Conditional rendering of Add Friend, Unfriend and Sent Follow Request button %>
<% if current_user.id != @user.id %>
    <% if current_user.following?(@user)%>
        <%= button_to "Unfriend",unfollow_path(@user),class:"flex border  w-48 h-10 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center mt-10"%>
    <% elsif current_user.sent_follow_request_to?(@user)%>
        <%= button_to "Cancel Friend Request",cancel_path(@user),class:"flex border  w-48 h-10 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center mt-10"%>
    <% elsif @user.sent_follow_request_to?(current_user)%>
        <div class="flex mt-4">
                    <%= button_to "Accept",accept_path(@user),class:"border border-black text-white px-3 py-2 rounded bg-blue-500 hover:scale-90 duration-200 "%>
                    <%= button_to "Decline",decline_path(@user),class:"mr-5 ml-3 border border-black bg-red-600 text-white px-3 py-2 rounded  hover:scale-90 duration-200 "%>
        </div>    
    <% else %>
        <%= button_to "Add Friend",follow_path(@user),class:"flex border  w-48 h-10 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center mt-10"%>
    <% end %>
<% end %>

<%# Displaying user friend request in the profile page-TEMPORARILY %>






</div>

<%# User Info Section on the right side of the  profile section %>


<div class="w-1/2 flex flex-col">
  <div class=" font-bold text-5xl m-2"> <%= @user.name  %> </div> 

  <div class=" text-xl flex m-3">



<%# I will add Font Awesome icons here. This is a temporary location icon %>
<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg>


<%# User Address %>
  <%= @user.area  %> <%= @user.city  %>, <%= @hash[@state.to_sym]
 %><%#= CS.state_name(@userparams)  %></div> 


<%# Hard coded values for age and bio. I will finish this part %>
  <p class="font-bold text-2xl mt-8"> Age <%= @user.age  %></p>
  <%= @user.bio  %> 


<%# Interest and experience section in the profile %>
  <h3 class="font-bold text-blue-700 mt-7 text-xl">Interests</h3>
  <div class="flex max-w-1/2  overflow-x-scroll max-w-1/3 mt-3  mr-24 ">

    <% @user.interests.each do |interest| %>

    <% if current_user == @user %>
        <%= link_to interest do %>
        <div class="border border-black rounded-md mx-3 py-2 px-4 flex flex-col items-start hover:bg-slate-200 hover:scale-105 duration-300 my-2">
        <p class="font-bold"> <%= interest.name %> </p>
        <p class="text-sm"><%= interest.experience %></p>
       </div>
        <% end %>
    <% else %>
        <div class="border border-black rounded-md mx-3 py-2 px-4 flex flex-col items-start hover:bg-slate-200 hover:scale-105 duration-300 my-2">
         <p class="font-bold"> <%= interest.name %> </p>
        <p class="text-sm"><%= interest.experience %></p></div>
<% end %>


    
    <% end %>
    

  </div>

 
 

  <% if current_user.id == @user.id %>

  <div class="flex">
   <%= link_to 'New interest', new_interest_path, class: "flex border border-black w-48 h-10 rounded-md b bg-blue-600  text-white hover:scale-90 duration-300  flex items-center justify-center mt-10 mr-10" %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete ,class:"flex border border-black bg-red-600   text-white w-48 h-10 rounded-md  hover:scale-90 duration-300  flex items-center justify-center mt-10 mr-10" %>
     </div>
  <% end %>
</div>

</div>
<div class="h-fit max-w-screen bg-slate-100 pb-20 ">
<h1 class="text-4xl font-bold  ml-64 mb-10"> Posts </h1>
<div class=' flex flex-col items-center justify-center my-2 grid grid-cols-3 pl-5 max-w-[75%] mx-auto gap-x-6  gap-y-8  '>
 <% @posts.each do |post| %>

    <div class="flex items-center justify-center group flex-col  hover:scale-105 duration-300 ">
    <div class="">

    <% if post&.image.attached?%>
        <%= link_to post_path(post) do %>
        <%= image_tag(post.image,class:"flex object-cover w-72 h-72 ");%><% end %>
    <% else%>
        <%= link_to post_path do %>
        <%= image_tag "account.jpg",class:"flex object-cover w-72 h-72";%><% end %>
    <% end %>
    </div>

    <div class="collapse group-hover:visible flex flex-col justify-start items-start w-72    rounded-b bg-black text-white pb-2">
    <p class="flex justify-start items-start ml-6 mt-2 font-bold"><%= post&.likes.count %> Likes </p>
    

    <p class=" flex justify-start items-start w-full ml-6 mt-2 "> <span class="mr-2 font-bold bg-"><%= post&.user.name  %></span><%= post&.caption%></p>
    </div>
    </div>

 <% end %> 

</div>
</div>


<%# redirect to signin page if no user is logged in %>
<% else %>
<% controller.redirect_to new_user_session_path %>
<% end %>