config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  resources :posts 
    resources :comments
  # end
  
  get 'search', to: 'profiles#search'
  get '/notif', to: 'profiles#acceptnotif'
  get '/feed', to: 'profiles#feed'
  get '/followrequests', to: 'profiles#followrequests'
  resources :interests

  resources :rooms, except: [:show] do
    resources :messages
  end
  
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }
  as :user do

    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    



  end
  get 'users/:id/message', to: 'users#showmessage', as: 'usermessage'
  post '/users/:id', to: 'users#destroy'


  resources :users,only: [:destroy,:show]
  

  post 'users/:id/follow', to:"users#follow", as: "follow"
  post 'users/:id/unfollow', to:"users#unfollow", as: "unfollow"
  post 'users/:id/accept', to:"users#accept", as: "accept"
  post 'users/:id/decline', to:"users#decline", as: "decline" 
  post 'users/:id/cancel', to:"users#cancel", as: "cancel"
  
  root to: 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end


# <div class="overflow-x-scroll flex w-[500px] max-w-lg mx-auto mt-3 flex border-b-2 pb-6"> 


# <div><div class="w-32 h-32 "> 
# <% users.each do |user|%>    
# <% if user.image.attached? %>
#     <%= link_to image_tag(user.image,class:"flex object-cover w-32 h-32  rounded-full"),user_path(user.id);%>
# <% else%>
#     <%=  link_to image_tag("account.jpg",class:"flex object-cover w-32 h-32  rounded-full"),user_path(user.id);%>
# <% end %></div>
# <p class="mt-2 font-bold"><%= user.name %></p><% end %>
# </div>

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment=@post.comments.build
    
    # update_comment
  end

  # GET /posts/new
  def new
    @post = Post.new
    @current=current_user
    @interest=[]
    @current.interests.each do |interest|
      @interest.append(interest.name)
    end


  end

  # GET /posts/1/edit
  def edit
    @current=current_user
    @interest=[]
    @current.interests.each do |interest|
      @interest.append(interest.name)
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    


    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # @post.user_id = current_user.id
      params.require(:post).permit(:user_id, :image, :caption, :category)
    end

    def update_comment
      render turbo_stream:
    
      turbo_stream.replace("post_comments_#{@post.id}",
            partial: "comments/commentbox",
            locals: { comment: @comment, post: @post }
          )
        
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.hidden_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
  <%= form.label :caption,'Caption',class:"mb-1" %>
    <%= form.text_field :caption, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5 flex flex-col">
    <%= form.label :category,'Select a Category',class:"mb-2" %>
    <%= form.select :category,options_for_select(@interest), include_blank: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="w-96 mx-auto">
  <p class="my-5">
    <strong class="block font-medium mb-1"></strong>
    <div class="flex justify-center">
      <div class="mb-3">
                        <% if post.user.image.attached?%>
                            <%= image_tag(post.user.image,class:"flex object-cover w-12 h-12  rounded-full border-2 border-blue-600 ");%>
                        <% else%>
                            <%= image_tag "account.jpg",class:"flex object-cover w-12 h-12  rounded-full border-2 border-blue-600";%>
                        <% end %>
                        </div>
      <div class="flex flex-col ml-3">
                        <span class="font-bold"><%= post.user.name %></span>
                        <%= post.user.city %>
                        </div>

      <div class="flex ml-auto self-end h-12 pt-0">
                            <% if current_user.id != post.user.id %>
                                <% if current_user.following?(post.user)%>
                                    <%= button_to "Unfriend",unfollow_path(post.user),class:"flex border  w-32 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center "%>
                                <% elsif current_user.sent_follow_request_to?(post.user)%>
                                    <%= button_to "Cancel Friend Request",cancel_path(post.user),class:"flex border   w-44 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-red-600 hover:text-white flex items-center justify-center "%>
                                <% elsif post.user.sent_follow_request_to?(current_user)%>
                                    <div class="flex mt-4">
                                                <%= button_to "Accept",accept_path(post.user),class:"border border-black text-white px-3 py-2 rounded bg-blue-500 hover:scale-90 duration-200 "%>
                                                <%= button_to "Decline",decline_path(post.user),class:"mr-5 ml-3 border border-black bg-red-600 text-white px-3 py-2 rounded  hover:scale-90 duration-200 "%>
                                    </div>    
                                <% else %>
                                    <%= button_to "Add Friend",follow_path(post.user),class:"flex border  w-32 h-8 rounded-md bg-black text-white hover:scale-90 duration-300 hover:bg-blue-600 hover:text-white flex items-center justify-center "%>
                                <% end %>
                                <% end %>
                        </div>
      
    </div>

    <% if post.image.attached?%>
      <%= image_tag (post.image) %>
    <% end %>
    

    <div class="mt-3  flex flex-row  border-b pb-2 border-inherit"> 
                <% like = current_user.likes.find_by(post: post)%>
                <%= render "likes/like", like: like, post: post%></div>


    <div class="flex pt-2 items-center">
                    <span class="font-bold bg-zinc-700 rounded-md px-4 py-1 text-white"><%= post.user.name %></span>
                    <span class="ml-3 font-semibold"><%= post.caption %></span>
                </div>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this post", post,data: { turbo_frame: "_top" }, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this post', edit_post_path(post),form: { data: { turbo_frame: "_top" } }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post_#{@post.id}" do %><div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div><% end %>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

   
   <div class="flex justify-between items-center">
 
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path,  class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">

    <%= render @posts %>
    

  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl mt-2">New post</h1>


  <%= render "form", post: @post %>




  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto  flex flex-col w-screen items-center justify-center ">
  <div class="ml-10 bg-slate-100 rounded my-10 pb-5">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <% if @post.user == current_user %>

    <div class="inline  mx-auto flex mt-3 w-96">

      <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded py-2 px-3 bg-gray-100  font-medium  w-40 h-12 flex items-center justify-center border border-black hover:scale-95 duration-300 hover:bg-blue-600 hover:text-white hover:border-none" %>
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded py-2 px-3 bg-gray-100 font-medium ml-2 w-40 h-12 flex items-center justify-center border border-black hover:scale-95 duration-300 hover:bg-red-600 hover:text-white hover:border-none" %>
      
    </div>
    <% end %>
  
  

<div class="ml-24"><%= render "comments/formforpost", comment: @comment%></div>
                <%= turbo_frame_tag "post_comments_#{@post.id}" do %>
                <div class=" overflow-y-scroll h-fit min-h-fit max-h-40 mt-6 ml-20 mx-auto w-80 pb-20">
                    <% @post.comments.each do |comment|%>
                        <%= render "comments/comment", comment: comment%>
                    <% end %>
                </div><% end %></div>